# Generated by Django 5.1.6 on 2025-02-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_secret_key_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hotp_counter',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
