# Generated by Django 5.2.3 on 2025-09-08 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='messages', to='chat.file'),
        ),
        migrations.CreateModel(
            name='MessageSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_seen_set', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_seen_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_messages', through='chat.MessageSeen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messageseen',
            index=models.Index(fields=['message', 'user'], name='chat_messag_message_9b03eb_idx'),
        ),
        migrations.AddIndex(
            model_name='messageseen',
            index=models.Index(fields=['user', 'seen_at'], name='chat_messag_user_id_2e8114_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageseen',
            unique_together={('message', 'user')},
        ),
    ]
