# Generated by Django 5.2.3 on 2025-08-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
