# Generated by Django 5.2.3 on 2025-08-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_content_type_alter_message_text_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, related_name='messages', to='chat.file'),
        ),
    ]
