# Generated by Django 5.2.3 on 2025-08-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_message_file_message_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='file',
            new_name='files',
        ),
    ]
