# Generated by Django 5.2.3 on 2025-08-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_file_message_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='http_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='profile_picuter',
            field=models.ImageField(blank=True, null=True, upload_to='chat_pics/'),
        ),
    ]
