# Generated by Django 5.2.3 on 2025-08-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatroom_bio_chatroom_http_link_chatroom_is_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
