# Generated by Django 5.2.3 on 2025-07-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base32_secret',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
