# Generated by Django 5.2.3 on 2025-07-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_donatelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatelink',
            name='amount',
        ),
    ]
